[package]
name = "iron-tera"
version = "0.1.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
description = "This is an Iron middleware for the Tera templating library"
repository = "https://github.com/leshow/iron-tera"
keywords = ["iron", "tera", "middleware", "templating"]
license = "MIT"

[dependencies]
iron = "0.4.0"
router = "0.4.0"
tera = "0.5.0"
serde = "0.8"
serde_json = "0.8"
serde_derive = "*"
